### ISSUE TITLE
Exception when generating handbook

### ISSUE THREAD

**Issue by MlgmXyysd** [Grasscutters/Grasscutter#17] opened 2022-04-19 05:01 UTC
```
D:\Grasscutter>java -jar grasscutter.jar -handbook
[12:59:46] [WARN] Could not find resource: data/AbilityEmbryos.json
[12:59:46] [INFO] Loaded 300 AvatarTalentDatas.
[12:59:46] [INFO] Loaded 400 AvatarSkillDatas.
[12:59:46] [INFO] Loaded 73 AvatarSkillDepotDatas.
[12:59:46] [INFO] Loaded 167 MonsterDescribeDatas.
[12:59:46] [INFO] Loaded 1 AvatarCostumeDatas.
[12:59:46] [INFO] Loaded 3032 NpcDatas.
[12:59:46] [INFO] Loaded 66 ReliquaryMainPropDatas.
[12:59:47] [INFO] Loaded 200 MonsterCurveDatas.
[12:59:47] [INFO] Loaded 90 AvatarLevelDatas.
[12:59:47] [INFO] Loaded 6889 ItemDatas.
[12:59:47] [INFO] Loaded 336 AvatarPromoteDatas.
[12:59:47] [INFO] Loaded 335 ReliquaryAffixDatas.
[12:59:47] [INFO] Loaded 90 WeaponLevelDatas.
[12:59:47] [INFO] Loaded 939 WeaponPromoteDatas.
[12:59:47] [INFO] Loaded 9 AvatarFlycloakDatas.
[12:59:47] [INFO] Loaded 6626 GadgetDatas.
[12:59:47] [INFO] Loaded 100 AvatarCurveDatas.
[12:59:47] [INFO] Loaded 42 ReliquarySetDatas.
[12:59:47] [INFO] Loaded 100 WeaponCurveDatas.
[12:59:47] [INFO] Loaded 744 EquipAffixDatas.
[12:59:47] [INFO] Loaded 60 PlayerLevelDatas.
[12:59:47] [INFO] Loaded 101 ReliquaryLevelDatas.
[12:59:47] [INFO] Loaded 2420 ProudSkillDatas.
[12:59:47] [INFO] Loaded 568 MonsterDatas.
[12:59:47] [INFO] Loaded 78 AvatarDatas.
Exception in thread "main" com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 22442 column 76 path $.
        at com.google.gson.Gson.fromJson(Gson.java:947)
        at com.google.gson.Gson.fromJson(Gson.java:897)
        at emu.grasscutter.tools.Tools.createGmHandbook(Tools.java:32)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:61)
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated object at line 22442 column 76 path $.
        at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1562)
        at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:490)
        at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:413)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:184)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
        at com.google.gson.Gson.fromJson(Gson.java:932)
        ... 3 more
```

**Comment by KingRainbow44** [comment] 2022-04-19 05:14
this might be a user error but ill have to check

**Comment by KingRainbow44** [comment] 2022-04-19 05:15
i dont even know what json its reading from

**Comment by memetrollsXD** [comment] 2022-04-19 14:05
Looks like one of your JSON files are misformed

**Comment by w4123** [comment] 2022-04-19 18:55
I encountered the same issue.
So the file is TextMap\TextMapEN.json
Line 22442 is
```json
"3606571930": "Fatui Advance Team Handbook, Appendix 4-4, Article 3：\"Sharing food and intel at the right moment is conducive to silencing a curious mouth.\" You're welcome.",
```
and the character S after the escaped quotation mark is column 76
Not sure why though

**Comment by w4123** [comment] 2022-04-19 19:17
After some testing, I suspect that the problem is related to the UTF-8 "：" character. Once I remove this character the error disappears.

**Comment by 34736384** [comment] 2022-04-20 04:54
I got the same problem and I'm not sure if it applies to you but I solved it by converting the file to ansi

**Comment by SunsetMkt** [comment] 2022-04-22 12:29
Got the same with https://github.com/Dimbreath/GenshinData/tree/master/BinOutput

```
Exception in thread "main" com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 103744 column 451 path $.
        at com.google.gson.Gson.fromJson(Gson.java:947)
        at com.google.gson.Gson.fromJson(Gson.java:897)
        at emu.grasscutter.tools.Tools.createGmHandbook(Tools.java:34)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:62)
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated object at line 103744 column 451 path $.
        at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1562)
        at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:490)
        at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:413)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:184)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
        at com.google.gson.Gson.fromJson(Gson.java:932)
        ... 3 more
```

Solved by save the `TextMap\TextMapEN.json` with ISO 8859-1 with VSCode.

**Comment by memetrollsXD** [comment] 2022-04-22 12:31
Please use the 2.6 version from
https://github.com/radioegor146/gi-bin-output

**Comment by SunsetMkt** [comment] 2022-04-22 12:37
> Please use the 2.6 version from https://github.com/radioegor146/gi-bin-output

Thanks, sincerely.

**Comment by PasserbyAlpha** [comment] 2022-04-23 06:25
It's because of the default charset that applied in different location. This bug should have been fixed in the latest stable branch, setting utf8 as the input and output charset for handbook.

**Closed** 2022-04-24 11:20 UTC
Labels: bug
